[project]
name = "chub-botv2"
version = "2.0.1"
description = "A complete recode of the CHUB Bot"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "disnake>=2.11.0",
    "motor>=3.7.1",
    "pymongo>=4.15.3",
]
